name: SSL certs Data Processing

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day
  workflow_dispatch:

jobs:
  process-data:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install requests
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run the script
        run: python "Lists/SSL CERTS/get_ssl_cert_list.py"

      - name: List files in the root directory
        run: ls -la

      - name: List files in the Lists/SSL CERTS directory
        run: ls -la "Lists/SSL CERTS/"

      - name: Move output files to correct directory (if necessary)
        run: |
          mv ssl_certificates_malicious_list.csv "Lists/SSL CERTS/" || echo "File not found in root."

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add "Lists/SSL CERTS/ssl_certificates_malicious_list.csv"
          git commit -m "Update ssl_certificates_malicious list" --allow-empty
          git push

      - name: Upload csv Results
        uses: actions/upload-artifact@v3
        with:
          name: hojacklibs-data-csv
          path: "Lists/SSL CERTS/ssl_certificates_malicious_list.csv"


